# Generated by Django 5.1.4 on 2025-04-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_produtoimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='produtos/padrao.jpg', upload_to=''),
        ),
    ]
