# Generated by Django 5.1.4 on 2025-04-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_alter_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('testmonial', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
