# Generated by Django 5.1.4 on 2025-04-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_testmonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonials',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
