# Generated by Django 5.1.4 on 2025-04-18 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_testmonials_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="O telefone deve estar no formato: '(99) 99999-9999'", regex='^\\(\\d{2}\\)\\s\\d{5}-\\d{4}$')])),
            ],
            options={
                'verbose_name': 'Informação de Contato',
                'verbose_name_plural': 'Informações de Contato',
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok'), ('outro', 'Outro')], max_length=20)),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['tipo', 'tipo'],
            },
        ),
    ]
