# Generated by Django 5.1.4 on 2025-04-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_informacaocontato_redesocial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testmonials',
            new_name='Testmonial',
        ),
    ]
