# Generated by Django 5.1.4 on 2025-04-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
