# Generated by Django 5.1.4 on 2025-05-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0014_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('paid', 'Pago'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('completed', 'Concluído')], default='pending', max_length=20),
        ),
    ]
