# Generated by Django 5.1.4 on 2025-05-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em processamento'), ('shipped', 'Enviado'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
